stages:
  data_ingestion:
    cmd: python src/lungCancerDetection/pipeline/stage_01_data_ingestion_pipeline.py
    deps:
      - src/lungCancerDetection/pipeline/stage_01_data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data/chest_ct_scan_images_dataset_modified

  prepare_base_model:
    cmd: python src/lungCancerDetection/pipeline/stage_02_prepare_base_model_pipeline.py
    deps:
      - src/lungCancerDetection/pipeline/stage_02_prepare_base_model_pipeline.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - CLASSES
      - PRE_TRAINED_LR
      - CLF_LR
      - REQUIRES_GRAD
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/lungCancerDetection/pipeline/stage_03_model_training_pipeline.py
    deps:
      - src/lungCancerDetection/pipeline/stage_03_model_training_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/data/chest_ct_scan_images_dataset_modified
      - artifacts/prepare_base_model
    params:
      - AUGMENTATION
      - BATCH_SIZE
      - EPOCHS
      - CLASSES
      - NUM_WORKERS
    outs:
      - artifacts/training/model.pth

  evaluation:
    cmd: python src/lungCancerDetection/pipeline/stage_04_model_evaluation_pipeline.py
    deps:
      - src/lungCancerDetection/pipeline/stage_04_model_evaluation_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/data/chest_ct_scan_images_dataset_modified
      - artifacts/training/model.pth
    params:
      - AUGMENTATION
      - BATCH_SIZE
      - EPOCHS
      - CLASSES
      - NUM_WORKERS
    metrics:
      - scores.json:
          cache: false
