artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1ugTPr_vzgB8cHk-_aE5tZx0GJXpoC9-S/view?usp=sharing
  local_data_file: artifacts/data_ingestion/chest_ct_scan_images_dataset_modified.zip
  unzip_dir: artifacts/data_ingestion/data
  unzip_dir_full: artifacts/data_ingestion/data/chest_ct_scan_images_dataset_modified

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.pth

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pth

evaluation:
  path_of_model: artifacts/training/model.pth
  val_data: artifacts/data_ingestion/data/chest_ct_scan_images_dataset_modified
  mlflow_uri: https://dagshub.com/kamran945/CV-Chest-Cancer-Detection-Project-MLflow-DVC.mlflow
